### ISSUE TITLE
Issue with license column

### ISSUE THREAD

**Issue by ZlataN25** [Elipse458/el_bwh#11]
Hello I am having an issue I never had before with el_bwh

![image](https://user-images.githubusercontent.com/68121443/87177620-f8f09780-c2a9-11ea-8690-289585ea7c8e.png)

Please let me know a possible fix for this, appreciated.

**Comment by KipxSateee** [comment]
@ZlataN25 That's not the entire error code, the "on duplicate key update" part is quite normal. If the user does not exist yet, it'll make said person in the database. Can you show us the entire error, especially the last part? It would be best to copy it and then redact all personal information.
