### ISSUE TITLE
[IDEA] Ban/kick after couple warns

### ISSUE THREAD

**Issue by Robijntjee** [Elipse458/el_bwh#2]
If a person gets warn, we can see that warn, but if poeple getting warned cuz the same thing, then they don't listen to the warns, so after a couple warns (configurable in config) they get a ban or kick (configurable in config), 

Easy to understand right?

###### Sorry for bad english!

**Comment by Scullyy** [comment]
People won't listen to the warns unless you enforce them, it's not up to the script when they ban/kick you it's up to the staff team, if you see someone has warns on record then kick them the next time, after that ban them, follow the strike system.

**Comment by Elipse458** [comment]
I'd like to leave this to the server owners & admins themselves, they should follow their own strike system as @Scullyy said.
