### ISSUE TITLE
Dont work correctly OneSync Infinity

### ISSUE THREAD

**Issue by johnsoul777** [Elipse458/el_bwh#22]
Now our server works with OneSync Infinity and it doesn't work correctly when you accept the report, it doesn't teleport the user ...

**Comment by TassieRPCx** [comment]
I am also aware of this issue, I will be looking into a fix and may post it to my own Github

**Comment by N-U-B** [comment]
Lazy prick above never fixed it.....

**Comment by TassieRPCx** [comment]
Eclipse made it infinity compatible hey thats sick

**Comment by Elipse458** [comment]
fixed in 1.7.1
