### ISSUE TITLE
Random UI Pop Ups

### ISSUE THREAD

**Issue by TinusNL** [Elipse458/el_bwh#27]
When i was playing on my server there something jsut randomly pop some messages up which look like they are from hackers. For example: "Hacked By ketamine bros". I didn't know what it was so i was gone search it out. Then i noticed that those ui's are inside the `iframe` of el_bwh. This btw only happens to admins. Is there any way of fixing/patching this? It also seams like there is a sortoff backdoor because it also happens if there is no one except for your self online (hacker might have been on the server before). 

I hope anyone can help me patch this because it is getting pretty anoying to be needing to rejoin everytime!

**Comment by Elipse458** [comment]
hey, does it happen when you open the banlist or warnlist? or it just happens whenever

**Comment by TinusNL** [comment]
It doesnt seem to be happening at a a specific poijt. Just random

**Comment by Elipse458** [comment]
fixed in 1.7.1
