### ISSUE TITLE
[BUG] Banning players won't work (only perm)

### ISSUE THREAD

**Issue by Robijntjee** [Elipse458/el_bwh#3]
When i want to ban a player, it bans the player, but it dont kick them out of the server.

**Comment by Elipse458** [comment]
Check the config and try enabling the backup kick method

**Comment by Scullyy** [comment]
Might be just you, I don't have an issue with this and I don't have backup kick enabled.

**Comment by Robijntjee** [comment]
Hmm, probably i fucked something up, when i changed the code. I will add it by myself ! :)

**Comment by Robijntjee** [comment]
Fixed it, and closed this issue.

**Comment by anthonyakilla93** [comment]
> Fixed it, and closed this issue.

Trying to add you on discord saying you are not accepting friends at this time
