### ISSUE TITLE
Not banning people

### ISSUE THREAD

**Issue by gfgbsimao** [Elipse458/el_bwh#35]
Hey i  own a fivem server that uses your script to ban people, one thing that i noticed is that i ban  a guy and it simply does nothing, the guy keeps playing and can connect to server

I use TxAdmin and fivem runtime 4045

**Comment by UsedRoleplay** [comment]
same, did you fix it?

**Comment by AnetteDieFette** [comment]
I have the same error please let me know if it is fixed or how it can be fixed

**Comment by gfgbsimao** [comment]
> I have the same error please let me know if it is fixed or how it can be fixed

Somehow, when i updated fxserver it fixed it self.
