### ISSUE TITLE
Warnlist 'UNKNOW'

### ISSUE THREAD

**Issue by kenjischier** [Elipse458/el_bwh#37]
Hi, in my warnlist it says by every user 'UNKNOWN'

![image](https://user-images.githubusercontent.com/90047999/139470216-61be7045-38e2-42f7-99fc-0691acc3a714.png)

**Comment by Elipse458** [comment]
hi, unfortunately, thats an issue with ESX versions > 1.2.0 which i wont be fixing in bwh 1,please wait for bwh2 or keep using it like this
