### ISSUE TITLE
SQL error: no name field

### ISSUE THREAD

**Issue by nap14hockey** [Elipse458/el_bwh#4]
[ERROR] [MySQL] [el_bwh] An error happens on MySQL for query "SELECT id,receiver,sender,reason,UNIX_TIMESTAMP(length) AS length,(SELECT name FROM users WHERE identifier=bwh_bans.sender) AS sender_name,unbanned FROM bwh_bans": ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'

After looking at Es_extended, there is no name field in the SQL database.

**Comment by Elipse458** [comment]
ah.. right.. the shitty update

**Comment by JonTronTheGreat** [comment]
#gay

**Comment by Elipse458** [comment]
just getting back to this, i haven't forgotten about it, i just don't have time for it rn, i'll do it in a few days

**Comment by Elipse458** [comment]
started working on update

**Comment by Elipse458** [comment]
pre-release of the update can be found on my discord, it works with the new shit esx versions
i'll fully release the update once i'm done with some more features but that pre-release has got all the core stuff working

**Comment by ManuDay** [comment]
If I may ask, how long would the new update for ESX take?

**Comment by Elipse458** [comment]
a version that works with the new esx is on my server in the releases channel, i'm just working on additional features, i'll release it later today

**Comment by ManuDay** [comment]
Ok, I could have a link for your Discord server

**Comment by Elipse458** [comment]
it's at the bottom of the readme in the repo

**Comment by ManuDay** [comment]
ok thanks

**Comment by Elipse458** [comment]
okay the update is done, i just need to test it properly, it'll get released tomorrow for sure

**Comment by Elipse458** [comment]
update released https://github.com/Elipse458/el_bwh/releases/tag/1.7
